services:
  postgres:
    image: postgres:17.2
    container_name: PostgreSQL
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: backend
    ports:
      - 5434:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql